godotengine/godot-vscode-plugin

src/gdscript/diagnostic.ts
Ignore keywords that are written in comment-blocks.
=> Ignore keywords in comments

README.md
Added the fix for my issue, as well as some spelling updates.
=> Update readme with spelling and FAQ

src/tool_manager.ts
For the editor path, we use PowerShell syntax, when required.
=> Added handling of paths with spaces in them

.gitignore, package-lock.json, package.json
Only affects development packages.
=> Dependencies all updated to latest versions.

package.json
Lint configuration, not configurations.
=> Fix small grammar issue

configurations/GDScript.tmLanguage.json
=> fix string literal highlighting

CHANGELOG.md, README.md
This makes the README look and feel more professional :slightly_smiling_face:
=> Improve the README and fix various typos

configurations/GDScript.tmLanguage.json
Fix #122 
To be frank, I didn't really read any documentation to do this, I just inferred things from the project's code itself. If there's any styling I messed up feel free to tell me to fix it.
=> Fix class_name statement bug

src/godot-tools.ts
=> check before calling platform-specific code

package.json
=> Use Properties syntax highlighting for `.import` files

src/debugger/server_controller.ts
- scene_file used an unnecessary call to path.relative that prevented proper use.
- If the debugger failed to launch, it would fail on future attempts.
=> Fix scene_file and launch failure bug

README.md
=> Add instructions on compiling extension to readme

.github/workflows/ci.yml, package-lock.json, package.json, src/godot-tools.ts, src/lsp/GDScriptLanguageClient.ts, src/lsp/MessageBuffer.ts, src/lsp/MessageIO.ts, src/lsp/NativeDocumentManager.ts, src/lsp/gdscript.capabilities.ts, tslint.json
The extension will be built and uploaded to artifacts so it can be tested easily by users.
This also fixes warnings reported by TSLint.
=> Set up continuous integration using GitHub Actions

src/debugger/commands/command_parser.ts
- Remove duplicate map entry "scene_tree" in CommandParser.
- Catch exception during trigger command: TypeError: class_name.replace is not a function. class_name is the key of Mediator.inspect_callbacks.
=> Add exception handling during trigger command

src/godot-tools.ts
=> Add check for PowerShell 7 executable name

README.md
Closes my issue https://github.com/godotengine/godot-vscode-plugin/issues/233
=> Document access to the class reference from the extension

src/debugger/mediator.ts
=> Clarify the function of the extra integer given by the debugger

syntaxes/GDScript.tmLanguage.json
=> Fixed the syntax of the escaped characters in strings

syntaxes/GDScript.tmLanguage.json
"remote" is currently not highlighted.
=> Add "remote" keyword for highlighting

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Preview:
- [Bug report](https://github.com/Calinou/godot-vscode-plugin/blob/add-issue-templates/.github/ISSUE_TEMPLATE/bug_report.yml)
- [Feature request](https://github.com/Calinou/godot-vscode-plugin/blob/add-issue-templates/.github/ISSUE_TEMPLATE/feature_request.yml)
=> Add GitHub issue templates

.github/workflows/ci.yml, README.md, package-lock.json, package.json
Local package installations should be favored over global installations to avoid conflicts when working on multiple projects on the same system.
Only dependencies that did not cause the build to break were updated.
- Add `package` npm script to run local vsce installation.
I built and installed the extension locally and can confirm it still works.
=> Update dependencies, recommend local TypeScript and vsce

syntaxes/GDScript.tmLanguage.json
=> Fix func keyword highlighting

configurations/snippets.json
`uinput` seems godot to me, err I mean good
=> Add "_unhandled_input" snippet

configurations/snippets.json
Adding the same contribution I did here: https://github.com/rafamadriz/friendly-snippets/pull/300
=> feat(snippets): add match statement

src/formatter/formatter.test.ts, src/formatter/snapshots/nodepaths/in.gd, src/formatter/snapshots/nodepaths/out.gd, src/formatter/textmate.ts, syntaxes/GDScript.tmLanguage.json
* fix highlighting for thing.CONSTANT
* fix snapshot tests failing due to line endings
* replace regex for bare nodepath shorthand (fixes #555)
=> Various highlighting/formatting fixes

src/debugger/godot3/server_controller.ts, src/debugger/godot4/server_controller.ts, src/extension.ts, src/lsp/ClientConnectionManager.ts, src/utils/project_utils.ts
This PR makes sure some previous PRs that improve editorPath handling are applied universally and do not conflict with each other.
=> Fix handling of editorPaths 

src/formatter/snapshots/nodepaths/in.gd, src/formatter/snapshots/nodepaths/out.gd, src/formatter/textmate.ts, syntaxes/GDScript.tmLanguage.json, syntaxes/examples/gdscript1.gd
=> Fix bare nodepaths referencing absolute/root paths

src/formatter/snapshots/operators.gd, src/formatter/textmate.ts, syntaxes/GDScript.tmLanguage.json
=> Formatting and Highlighting Fixes

src/lsp/GDScriptLanguageClient.ts
Clientside hotfix for #820.
This suppresses the annoying error notification from the failed request.
@Calinou I could add a notification saying that an LSP request failed and suggesting that they move `class_name` to not be at the top of their file? 
Something like this?
=> Add ability to suppress LSP error messages
