godotengine/godot-vscode-plugin

- package.json
- src/gdscript/definitionprovider.ts
- src/tool_manager.ts
In some cases godot project can be in the separate folder of main project, I have added configuration parameter to handle this case.
> Add project root configuration settings

- src/gdscript/diagnostic.ts
This fixes the issue where single line if-else statements are diagnosed as an error:
```gdscript
variable = true if x == y else false
```
The regex(`.*?if.*else.*`) might be too broad though...
> single line if-else statement

- src/tool_manager.ts
I often find myself with multiple game windows when running projects using this extension.
I prefer Godot's editor behavior of closing the existing game windows before launching another instance.
This PR adds a simple check followed by `Terminal#dispose` if a terminal found with the same name as our extension ones is found. Terminals are renamed to a more specific "GodotTools" to avoid a very hypothetical conflict with another extension.
Cheers,
> Close existing terminal when executing "run" commands

- configurations/GDScript.tmLanguage.json
- configurations/gdscript-configuration.json
- configurations/snippets.json
Added following things in grammar & configuration:
Folding
Added new keywords such as: switch, preload, assert, etc matching with current version of gdscript documentation
"//" style comment at the top of snippets.json was causing a problem hence removed it (it's redundant)
> minor addition in configuration and grammar files

- configurations/GDScript.full.tmLanguage.json
- configurations/GDScript.tmLanguage.json
This adds the `class_name` keyword that was added to Godot 3.1.
PS: What's the difference between `GDScript.full.tmLanguage.json` and `GDScript.tmLanguage.json`? Are these used in different contexts?
> Add `class_name` keyword to syntax highlighting

- src/tool_manager.ts
Plugin doesn't seem to work on any of my linux machines. This shell var seems to be null on linux. Seems like it might be the case on MacOS too. When its null the console reports a lack of `endsWith` method on the null var. I am adding a fallback for the shell var that is an empty string. I am not sure if this is the best way to fix. But it does the trick for me.
> Add fallback for shell var

- configurations/GDScript.tmLanguage.json
Currently, any occurrences of PascalCase identifiers (even as parts of other words) are recognized as classes.
This assumes snake_case convention for all methods and variables and makes it impossible to use camelCase. While this is the recommended GDScript style, the syntax highlighter should allow for different styles as long as it can do so unambiguously. This is already done for existing rules, but overridden by one rule with an overly general regex pattern.
This commit modifies the catch-all rule for the `parscal_class` group to only capture whole words.
For clarity, it renames `parscal_class` to `pascal_case_class`.
Before:
After:
> Fix syntax highlighting for camelCase identifiers

- src/debugger/debugger_context.ts
When a launch.json is not found, the code that creates a temporary default configuration couldn't find the project.godot file as it didn't use the file system path, just the folder name. As a result, it couldn't find project.godot even when one was there.
Fixes #167
> Fix default debug config not using full filepath

- src/debugger/mediator.ts
Or rather, the output window never got created. This was an oversight that didn't get caught during the refactoring.
Fixes #173
> Fix debugger not showing output text

- configurations/snippets.json
- Remove `set_process(true)`/`set_process_input(true)` snippets since these are enabled automatically in Godot 3.0 onwards.
> Remove `extends` snippet which no longer works since Godot 3.0

- src/debugger/debug_session.ts
It appears that the way VSCode determines what breakpoint is toggled is via a sorted array of IDs instead of line numbers, so the arguments that the setBreakpointRerquests would send were not guaranteed to be in order.
Fixes #215
> Fix breakpoints out of order and confusing VSCode

- README.md
- package.json
- src/debugger/debug_session.ts
- src/debugger/mediator.ts
- src/debugger/scene_tree/inspector_provider.ts
- src/debugger/scene_tree/scene_tree_provider.ts
- src/debugger/server_controller.ts
This would prevent the socket from cleaning up, so it wouldn't send messages to the debugger. Fixes #175 
Also removes an unnecessary await that, for some people, caused breakpoints to be set before debugger was configured. Fixes #168
> Fix debug server not closing properly, fix set breakpoints before project path is set

- package.json
- src/debugger/debug_session.ts
- src/godot-tools.ts
Right clicking on a .tscn file will allow you to press "Set as Scene File" and set that file as the debugger's scene_file ([line 187 of package.json](https://github.com/godotengine/godot-vscode-plugin/blob/master/package.json#L187-L191))
This is done by setting an additional workspace configuration "godot_tools.scene_file_config". 
-If godot_tools.scene_file_config is set through right click, it overrides "scene_file" found in     launch.json. The value of "scene_file", however, remains untouched.
-Right Clicking the same .tscn file as scene_file_config and pressing "Set as Scene File" will unset scene_file_config
> Add ability for user to set scene file on right click in explorer

- src/lsp/NativeDocumentManager.ts
The way messages are sent to the LSP server via TCP is slightly different between 3.1 websocket and 3.2 TCP/IP, requiring a header indicating the length of the message and a JSON object with a signature that requires a params: key that was lacking, and no ID.
Fixes #210 
Also adds the Find widget to the native symbol pages that come up so you can CTRL+F through a page.
> Fix no header, non-TCP compliant msg for natives

- package.json
Fixes #240.
As said in the issue comment :
> I don't know what is its initial intended behaviour. I think it's just to hide the indicator at the bottom right of the editor, since disabling the status check is not possible.
> 
> If you know the original intent of that option please let me know.
> Remove the configuration item 'godot-tools.check_config' as it has no effect

- syntaxes/GDScript.tmLanguage.json
- syntaxes/README.md
- Changed regex to allow only valid paths as discussed in #275 
- Added a `README.md` with useful information for debugging and creating regexes for the GDScript syntax.
> Change `$` node path shorthand regex to match only valid paths

- src/debugger/debug_session.ts
Despite `supportsConditionalBreakpoints` being set to `false`, seems the debug adapter still expects the debugger to explicitly filter out conditional breakpoints, or continue treating them as regular breakpoints (which makes the presence of `supportsConditionalBReakpoint` kind of pointless? I dunno.)
Until Godot supports conditional breakpoints, I'm opting to just remove them entirely as there's no feasible way of hooking into the debugger so there's no confusion. Now they'll be ignored.
Fixes #267
> Fix conditional breakpoints being parsed as regular breakpoints

- src/lsp/NativeDocumentManager.ts
- src/lsp/gdscript.capabilities.ts
Since Godot uses the `SymbolKind` enum defined by the [LSP protocol](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol) instead of the one defined by [VSCode](https://github.com/microsoft/vscode/blob/459ffea03c117042c17c6a3c02f066c4af5db555/src/vs/editor/common/languages.ts#L1175-L1202).
This enum was changed in Godot in https://github.com/godotengine/godot/pull/50913 and was backported to 3.x in https://github.com/godotengine/godot/pull/50914.
Also fixes `marked` being called incorrectly to parse codeblocks.
Fixes #321
> Use the LSP defined SymbolKind enum and fix marked

- src/debugger/debug_runtime.ts
Fixes issue #296
When starting a new debug session a `setBreakPointsRequest()` is triggered for each file that contains breakpoints.
However at that time `this.project_path` is still undefined. It will only be initialized during the `launchRequest()`.
Trying to pass `undefined` into `path.relative()` will cause a type error which means the `setBreakPointsRequest()` will fail and exit after the first breakpoint of each file.
With this fix we skip the respective lines during initialization.
At that time the `project_path` is still unknown so we can't construct the relative path.
Also the Mediator isn't connected yet, so these lines wouldn't do anything anyway.
> Fix "Continue" for multiple breakpoints in the same script

- src/debugger/debug_session.ts
We have to send a response to the `configurationDoneRequest` or else vscode will run into a timeout and disconnect the debug adapter. For some reason this timeout does not apply when launching the session initially. That's why stopping and then starting a new session worked before.
Fixes #282
> Fix restart of debugging sessions

- syntaxes/GDScript.tmLanguage.json
This pull request makes the syntax highlighting of GDScript more closely match the built-in Godot editor's, as well as VSCode's Python syntax highlighting.
Before:
After:
Godot editor:
VSCode Python:
> Improve syntax highlighting

- configurations/gdscript-configuration.json
When declare `static func` and press enter key, two indents will be generated. 
Fix by add "static func" pattern
> Fix "static func" indent error

- src/godot-tools.ts
This `escape_command` essentially cares about one thing: Is the integrated terminal using PowerShell or not.
Note that VS Code has a new way of setting the integrated terminal - now they use profiles. There is a default profile for PowerShell. You can also set custom profiles, and those profiles can either be based on one of the default profiles (using `source`), or an executable (using `path`).
Also note that the deprecated `terminal.integrated.shell.${os}` definition currently overrides the new `terminal.integrated.defaultProfile.${os}`.
With that being said, I've tested this new code with:
* MacOS
* terminal set as `zsh` (just ensuring that non-Windows usage is not broken by this change)
* Windows:
* shell set to PowerShell executable (`"terminal.integrated.shell.windows": …
> fixes #302 handling of Windows terminals determined by profiles

- README.md
Dug around for this for a while until finding a random steam thread: https://steamcommunity.com/app/404790/discussions/0/2579854400740817169/
Adding to the README for future travelers
> Add macOS editor location to README since it's not obvious

- syntaxes/GDScript.tmLanguage.json
The regex now supports:
- Unquoted node paths with numbers eg. `$Node2D/Area2D`
- Single-quoted node paths eg. `$'Node/Sprite'`
- Quoted node paths with spaces eg. `$"Node/Main Menu"`
Old regex syntax diagram:
New regex syntax diagram:
> Fix some `$` node path shorthand regex bugs in syntax highlighting

- package.json
- src/godot-tools.ts
This is a resubmission of #317, with the feature correctly in its own branch. I should be able to keep up with upstream changes now.
>This addresses issue https://github.com/godotengine/godot-vscode-plugin/issues/156 by automatically attempting to reconnect to the language server.
>
>This adds 3 new settings: reconnect_automatically, reconnect_cooldown, and reconnect_attempts.
>
>The default values are to attempt to reconnect once per second, for 10 seconds, after which it displays the existing "Couldn't connect" error message.
> Add configurable auto-reconnect

- syntaxes/GDScript.tmLanguage.json
I missed a couple of functions that should have the special highlighting for NodePath parameters.
> Add missing NodePath-using functions

- syntaxes/.prettierrc.json
- syntaxes/GDScript.tmLanguage.json
- syntaxes/examples/gdscript1.gd
Some instances of keywords followed by an open paren were being incorrectly highlighted as a function call. 
I also added a `.prettierrc.json` config file to the syntaxes directory. I would really like to reach the point where the entire project has automatic formatting preconfigured, maybe including precommit hooks, but I'm starting with the folder I've touched the most.
(Also: hopefully I got all the trailing newlines correct this time...)
<details>
<summary>Screenshot</summary>
</details>
> Fix keywords being incorrectly highlighted as function calls

- package-lock.json
- package.json
- src/godot-tools.ts
Added an option to copy a file's resource path to the system clipboard, accessible at:
- file explorer's context menu
- editor tab title context menu
- the command palette(targeting the file in the last active editor)
Additionally, I fixed the technique used to resolve the `project.godot` config file. Previously, it assumed that the file was located in the root of the VSCode workspace, but that's not guaranteed to be the case.
I had to add a dependency to do this(klaw, for recursively directory searching), but I'm not 100% clear on how package-lock.json works and what I'm supposed to commit. I also don't know how the releases work, so hopefully @Calinou will let me know if I broke something.
Related future work:
- add a command palette command to grab the resource path of the currently …
> Add context menu options to copy resource path

- src/godot-tools.ts
See https://github.com/godotengine/godot-vscode-plugin/issues/356.
@DaelonSuzuka Could you take a look to make sure the message is well-worded?
> Mention that the Godot editor must be running in connection error message

- .gitignore
Having a `workspace.code-workspace` file in the root of this workspace will cause the Extension Development Host to automatically open the specified folder. 
I'm adding this to the gitignore instead of committing a workspace file directly because I often want to specify a real project for testing, and that local path obviously shouldn't be committed.
This workspace file will cause the Extension Development Host to open the godot-tools folder as a workspace. Simply replace the path with a path to a real project to open that instead.
```json
{
"folders": [
{
"path": "."
}
]
}
```
> Add workspace file to `.gitignore`

- src/debugger/server_controller.ts
A previous commit assembled the `executable_line` variable incorrectly, and added redundant local variables.
This is a fix for #370. I can confirm that in `1.3,0`, launching is slower and breakpoints don't stop. This change fixes that regression.
However, on `1.2.0`, `1.3.0`, _and_ this patch, continuing or stepping over/in/out of a stopped breakpoint doesn't seem to do anything. I have to admit I've never used the VSCode debugger until now, so I'm not sure if this is a known issue, a problem with my configuration, or another regression.
> Fix regression in launching debugger

- syntaxes/GDShader.tmLanguage.json
- syntaxes/examples/example.gdshader
Thanks to a generous contribution from @AlfishSoftware, we have a brand new, custom built gdshader syntax. 
@Calinou Are you aware of any changes in the gdshader language from Godot3 to Godot4 that might cause a problem here? I have to admit I've barely touched shaders in Godot3, and I have absolutely no idea what's been added or removed in 4.
The following screenshots show the before/after comparison, as well as a shader embedded in a resource file:
> Replace temporary `.gdshader` syntax with more extensive support

- package-lock.json
- package.json
- src/lsp/NativeDocumentManager.ts
Currently the documentation opens every new symbol in a separate web view window which quickly makes the workspace messy, if users navigate to nested symbols (open symbol docs from already opened documentation window). The PR addresses this issue in the following way:
- Opens symbol documentation window in new column or nearest non-editor column (user opens the documentation for the first time or has the documentation already open, switches to the editor and opens another symbol)
- Opens symbol documentation window in current column if it is a  non-editor column (user has the documentation already open and focused, then opens another symbol or clicks on a symbol link)
- Adds simple configuration that lets user switch to additional `active` placement option
- `active` placement always …
> Improve displaying symbols documentation

- package.json
- src/debugger/debug_session.ts
- src/debugger/debugger_context.ts
- src/debugger/mediator.ts
- src/debugger/server_controller.ts
This PR implements #362.  
This allows other VSCode plugins to fully leverage the debugger interface that this plugin provides.  `additional_options` lets any other plugin specify whatever arguments it wants to send to the debugger.
```
class GodotDebugConfiguration implements vscode.DebugConfiguration{
public type = "godot";
public name = "Debug Godot";
public request = "launch";
public project = "${workspaceFolder}";
public port = 6007;
public address = "127.0.0.1";
public launch_game_instance = true;
public launch_scene = false;
public additional_options = "";
}
private runGutThroughDebugger(options:string = ''){
let config = new GodotDebugConfiguration();
config.additional_options = "-s \"res://addons/gut/gut_cmdln.gd\"";
vscode.debug.startDebugging(undefined, config);
}
```
> Add "additional options" to launch debugger with

- package.json
- src/godot-tools.ts
- src/lsp/GDScriptLanguageClient.ts
- src/lsp/NativeDocumentManager.ts
This adds an editor context menu option to open the symbol docs for the selected word, or the word under the cursor.
Open questions:
https://user-images.githubusercontent.com/18042232/184232546-99a089d5-ca62-4ece-a291-b4c87293a4bf.mp4
Special thanks to @tomwyr, since this builds directly on his PR that fixes the doc viewer behavior.
> Add "Open Type Documentation" context menu option

- syntaxes/GDScript.tmLanguage.json
- syntaxes/examples/gdscript1.gd
Fixes #418.
I had to completely rebuild the variable declaration rule to fix this bug.
Along the way, I removed some unused junk and standardized the names of all the rules. Some rules had `hyphenated-names` and some had `underscore_names`. Underscore names are easier for to work with in various text selection operations, so I switched all the hyphens to underscores.
> Fix incorrect highlighting in dictionary literals

- syntaxes/GDResource.tmLanguage.json
- syntaxes/GDScript.tmLanguage.json
- syntaxes/GDShader.tmLanguage.json
- syntaxes/examples/example2.gdshader
- syntaxes/examples/gdscript1.gd
Per #415, this PR fixes some regexes that appeared to work in VSCode/onigumura but do not work in linguist using PCRE.
When this PR is done, I need to remember to post in github/linguist#3924 and let the linguist project know that we've fixed our grammars.
Additionally, @lildude has documented a process [here](https://github.com/godotengine/godot-vscode-plugin/issues/415#issuecomment-1237132824) that we can use to verify that these changes satisfy `linguist`'s requirements. It's worth investigating if this process or a derivative can be integrated into our CI, which will at least provide syntax validation of our grammar files.
All three of the errors are invalid uses of positive lookbehind using a non-fixed length.
Problem areas:
- …
> Fix errors in grammar syntax

- package-lock.json
- package.json
- src/document_link_provider.ts
- src/godot-tools.ts
- src/utils.ts
This should be a fix for #435.
Apparently, the plugin would fail to initialize if you were starting VSCode without a workspace. I exclusively open folders as workspaces, so I never thought to test this scenario.
The failure is because the plugin was trying to find `project.godot` when it activated, and several things assumed that would never fail. I've completely removed this search from the plugin activation and every place that needs the project file/directory now just looks it up when it needs it.
This also means I can remove a dependency (klaw), which is always good.
> Clean up plugin initialization process

- syntaxes/GDScript.tmLanguage.json
- syntaxes/examples/gdscript1.gd
This fixes a number of minor syntax highlighting problems I've identified.
This one's a bit wierd:
v1.3.1:
current master:
This PR:
I've seen some problems with Godot 4 syntax, too, but unfortunately I wasn't smart enough to make notes on all of them. I'm going to do some work in Godot 4 this weekend, and if I see anything weird I'll try to get it added to this PR.
> Fix various syntax highlighting problems

- src/godot-tools.ts
#439 apparently had a couple accidents, a leftover log statement and a reference to a removed class variable, `workspace_dir`.
The reference to `workspace_dir` affects the code path for launching the Godot editor from VSCode, and that feature still works even when I remove the entire line. I didn't write this feature, and I don't see a purpose for this line in the first place.
> Fix errors left after cleaning up plugin initialization process

- src/godot-tools.ts
Fixes issue where port isnt respected after changed in vscode settings.
> Fix spelling mistake when getting port and host from configuration

- src/utils.ts
> Fix wrong `section-identifier` used to retrieve configuration

- syntaxes/GDScript.tmLanguage.json
- syntaxes/examples/gdscript1.gd
- syntaxes/examples/gdscript2.gd
- binary int notation
- `_` spacers in numeric literals
- fixed several instances of incorrect case insensitivity
- @"a", &"b", ^"c", and r"d" style string literals
> Multiple highlighting improvements

- src/lsp/ClientConnectionManager.ts
Fixes #512
The Headless LSP child process had no stderr handler due to developer laziness, and in some situations this causes the process to stop responding to events.
I still don't want to see stderr in the output, but providing an empty lambda handler should hopefully prevent the process from hanging.
> Fix Headless LSP not starting

- syntaxes/GDScript.tmLanguage.json
* Adds the upcoming `@abstract` annotation https://github.com/godotengine/godot/pull/82987 (4.3) to the list of annotations in the gdscript textmate grammar. ~~will move to a new PR~~ nvm
* Complete syntax highlighting for properties. Class properties used to be unhighlighted (the only properties highlighted were `.` properties) and are now highlighted properly as `variable.other.property.gdscript`
* Treat `void` as a `keyword` instead of a `class`. See https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/modules/gdscript/gdscript_tokenizer.h#L130C4-L130C8 (gdscript considers `void` to be a keyword, similar to C-style languages)
NOTE: This is my first time working with regular expressions, so please let me know if I've made a mistake with my added regular …
> Syntax highlighting changes

- src/logger.ts
- src/lsp/ClientConnectionManager.ts
- src/lsp/GDScriptLanguageClient.ts
- src/lsp/NativeDocumentManager.ts
- src/utils.ts
This PR internally splits the LSP client connection behavior based on backend 'target". The two possible targets are `HEADLESS` and `EDITOR`
When attempting to connect to an `EDITOR` LSP, if the value of `godotTools.lsp.serverPort` is either `6005` or `6008`, the client will try both ports in succession on each attempt. 
The end result is that with default Godot EditorSettings and default extension settings, the language server should Just Work:tm:, no matter what version of Godot is being used.
I'm considering renaming `godotTools.lsp.serverPort` and `godotTools.lsp.serverHost`, to soft-reset users to the ideal default values.
> Improve LSP connection behavior (fixes Godot3/4 port issue)

- src/debugger/godot3/server_controller.ts
- src/debugger/godot4/server_controller.ts
- src/extension.ts
- src/lsp/ClientConnectionManager.ts
The previous version detection would fail to detect some versions of godot (e.g 4.1.1.stable.mono.official.bd6af8e0e), resulting in an unclear error message. This commit makes a minor change to slightly improve the robustness of the version detection regex.
With this change I can run and debug my project with godot 4.1.1, and breakpoints even work 😄
> Adjust Godot version detection regex

- src/lsp/GDScriptLanguageClient.ts
- src/providers/documentation_builder.ts
Fixes the issue of [br] bbcode's weren't rendering new lines.
> Fix BBCode [br] not rendering in hover

- package.json
- src/extension.ts
Per feedback from @KoBeWi, this PR moves the process started by `Open Workspace with Godot Editor` back to a terminal (instead of a headless child process).
This time the terminal is implemented correctly, with a name + icon, and doesn't have a lingering prompt that you really shouldn't use. It also prints that the editor was stopped and what the exit code was.
Notes:
- Killing the terminal in VSCode (trash can button) kills the Godot Editor.
- Closing the Godot Editor _does not_ kill the terminal, just in case there's some output you wanted to see.
- Running `Open Workspace with Godot Editor` again will close any existing windows and start a new one. I don't see a reason to open the same workspace multiple times.
- new settings:
- `godotTools.editor.verbose`: Whether to launch the Godot …
> Launching the editor opens a new custom terminal

- src/debugger/godot4/server_controller.ts
Before fix
After fix
The server_controller of Godot 3 has no this bug.  So only fix for Godot 4.
> fix Godot4.x debug console print multiple logs into one line.

- .gitignore
- package.json
- src/debugger/debugger.ts
- src/debugger/godot3/server_controller.ts
- src/debugger/godot4/server_controller.ts
- src/extension.ts
- src/formatter/textmate.ts
- src/lsp/ClientConnectionManager.ts
- src/utils/project_utils.ts
This should resolve #570 and #574.
`editorPath.godot3/4` setting and `editor_path` debug configuration now correctly handle paths with spaces or surrounded with quotes.
The Godot exe version check was missing quotes, so paths with strings were failing the test even thought the actual debugger handles it correctly.
Added validation to the debug config values for `address` and `port` to prevent weird, obviously wrong stuff from happening.
Fixed the debug config value `editor_path` not being used.
Also applied better path handling to "launch godot editor" command.
> Improve path handling when starting processes

- src/extension.ts
- src/utils/project_utils.ts
This PR adds a `godotTools.getGodotPath` command so that other extensions that rely on this one can get the path to the executable without having to determine the version of the current project and then decide which configuration value to use (`godotTools.editorPath.godot3/4`).
Usage:
In another VSCode extension use the following to get the path to the Godot executable for the currently opened project
``` typescript
let editorPath : string = await vscode.commands.executeCommand('godotTools.getGodotPath');
```
I maintain the [gut-extension](https://github.com/bitwes/gut-extension) plugin that allows you to run GUT unit tests through VSCode.  It was using `godot_tools.editor_path` to launch Godot.  I was starting to adjust my code to determine which configuration value to use when I …
> Expose Godot path as getGodotPath command

- package.json
- src/providers/inlay_hints.ts
Adds #588, creating inlay hints in GDScript files
Currently works with Godot 3.x and 4.x (tested on the latest stable of both; 4.2 and 3.5.3)
> Add basic inlay hint support for GDScript

- package.json
- src/utils/project_utils.ts
I was using --help to check the version of the specified Godot binary, because it's output is more specific (it includes the words "Godot Engine").
However, Godot 4.3 adds color to the output of --help, and this breaks the regex used to validate the version number.
The extra strictness of using --help is probably overkill, so I'm just switching back to --version.
This PR also changes the default value of `godotTools.editorPath.godot4` from `godot4` to just `godot`.
fixes #585
> Fix version check of Godot binary 

- syntaxes/GDScript.tmLanguage.json
- syntaxes/examples/gdscript2.gd
fixes #591
fixes single line set/get in Godot 4:
> Syntax highlighting fixes

- src/providers/documentation.ts
- src/providers/hover.ts
- src/utils/project_utils.ts
- Fixed document links not working in scene files
- Fixed a type error in the documentation provider when receiving class info from the LSP
- Added support for image previews when hovering on document links
- Added support for image previews in `ExtResource()` hovers
> Fix issues with feature providers

- src/scene_tools/parser.ts
Fixes #600
The Scene Preview panel was failing to render certain scene files. The cause turned out to be a new(?) field in the node section header, `nodes_paths`.
These section headers were being found and parsed in a single overly-large regex, which did not tolerate the addition of the new field. The fix is splitting the work into one regex that finds the section header, and mutlple smaller regexes that extract each field individually.
> Fix broken scene file parser

- src/utils/subspawn.ts
Currently, headless LSP processes continue running when VS Code exits on Linux.
**Simple steps to reproduce:**
1. Launch VS Code.
2. Check the headless processes ― for example, with `ps ajx | grep headless`.
Here's the output on my machine:
```
vpyatnitskiy@vpyatnitskiy-katana:~/tmp/godot-vscode-plugin$ ps ajx | grep headless
26910   27154   27154   27154 ?             -1 Ss    1000   0:00 /bin/sh -c "/home/vpyatnitskiy/.local/share/Steam/steamapps/common/Godot Engine/godot.x11.opt.tools.64" --path "/home/vpyatnitskiy/godot-projects/Left or Right" --editor --headless --no-window --lsp-port 38661
27154   27159   27154   27154 ?             -1 Rl    1000   0:01 /home/vpyatnitskiy/.local/share/Steam/steamapps/common/Godot Engine/godot.x11.opt.tools.64 --path …
```
> Fix child processes not being killed properly

- media/docs.css
Improves codeblock highlighting by:
-  Adding context to the codeblock detailing which language the following code is.
-  Setting the `pre` block's background to match the default background for `code` blocks to give a consistent experience.
-  Setting a border radius for the `pre` block double that of the `code` block's default (4px, which is hard-coded).
Works on class documentation blocks and `li` code blocks for properties/members/methods.
**Before**
**After**
> Improve codeblock formatting in documentation

- src/lsp/ClientConnectionManager.ts
- src/lsp/GDScriptLanguageClient.ts
Should fix #636.
The internal count of connection attempts was incorrectly not being reset when a connection is actually established. This caused the connection retry to fail after several successful reconnections.
> Fix LSP connection attempts not resetting

- src/utils/index.ts
- src/utils/project_utils.ts
Fix a problem that when `project.godot` is excluded in VSCode, `get_project_version` function will always return `undefined`
**How to reproduce:**
1. Add `project.godot` into vscode settings
2. Run **open workspace with Godot Editor**
There will be an error popup that the current workspace is not a godot project
**There is a simple fix:**
The `findFiles` api support taking a `null` value in the second parameter, then it will not take any exclusion from user config.
https://code.visualstudio.com/api/references/vscode-api
> Fix project not found when `project.godot` file is excluded

- src/providers/documentation_builder.ts
It seems the extended inheritance chain previously being parsed is no longer available, which causes the "Inherits: " information to be empty. Inspecting the symbol information available, it seems there is no way to recover the inheritance chain without additional queries or modifying LSP response, so a quick fix to display the correct information that we do have is an incremental improvement.
**Before**
**After**
> Fix poor documentation formatting of class titles and inheritance chain

- src/debugger/godot3/server_controller.ts
- src/debugger/godot4/server_controller.ts
This is a follow-up for https://github.com/godotengine/godot-vscode-plugin/pull/613. Both PRs need to be merged for this change to work.
**Issue:**
On Linux, when debugging session is initiated and then closed from VS Code, the game (i.e. the process being debugged) does not terminate.
**Steps to reproduce** are as you would expect:
1. Have a launch configuration for GDScript in VS Code properly set up.
2. Launch a project with F5.
3. Switch back to VS Code. Press Shift+F5 to close the debugging session.
4. The session closes but the project continues running.
**Cause:**
- Similar to https://github.com/godotengine/godot-vscode-plugin/pull/613, the debugger process is started with `shell: true` flag, which causes `child_process.spawn()` to first start a shell process which, in turn, starts …
> Fix debugged process not being terminated when debugging session closes on Linux

- src/debugger/godot3/server_controller.ts
- src/debugger/godot4/server_controller.ts
- src/extension.ts
- src/lsp/ClientConnectionManager.ts
- src/utils/project_utils.ts
Should fix #654
Relative path values for `editorPath.godot3` and `editorPath.godot4` were failing to resolve properly. This PR should fix that behavior, plus standardize all the places the editorPath is being retrieved, so the same sanitization and path resolution is used everywhere.
> Fix relative godotPath values not resolving correctly

- src/utils/project_utils.ts
fixes: https://github.com/godotengine/godot-vscode-plugin/issues/598
This will automatically resolve to the path of the Godot executable if a .app bundle is supplied, instead of needing to drill down into the bundle and find where it's located.
> improve macOS path resolution for app bundles

- package.json
- src/scene_tools/preview.ts
"Pinning" a scene in the Scene Preview was  being confused with "pinning" a scene as the debug/launch target.
Renaming it to "locking" and changing the associated icons should help prevent this confusion in the future.
> Improve Scene Preview ergonomics

- src/debugger/godot3/server_controller.ts
- src/debugger/godot4/server_controller.ts
This PR is the first commit of #662, cherry picked to preserve authorship.
Later commits in the PR break debugging, but this first commit is a good change and I'd like to merge it sooner than later.
> Fix object id decoded as wrong signedness.

- package-lock.json
- package.json
- syntaxes/GDScript.tmLanguage.json
> Fix various syntax highlighting issues

- src/providers/documentation_builder.ts
ya-bbcode does not consider skip-lint to be an attribute, and it turns into the tag '[code skip-lint]' which won't match with the closing tag `[/code]`, leading to broken formatting.
I don't know if its valid bbcode or not, but Godot docs have it, for example the `Control` class documentation.
> fix format_documentation for `[code skip-lint]`

- syntaxes/GDScript.tmLanguage.json
I noticed that @export_storage for 4.3 has not been added yet to the syntax
> Add `@export_custom` and `@export_storage` to syntax highlighting

- package.json
This change shouldn't have any actual effect, but I noticed that some file extensions were listed with a period and some weren't. Both styles appear to function the same, but the [language contribution point docs](https://code.visualstudio.com/api/references/contribution-points#contributes.languages) use a period, so I've standardized ours to be the same.
> Standardize contributed language's extensions

- media/docs.css
- package.json
- src/providers/document_link.ts
- src/providers/documentation.ts
- src/providers/documentation_builder.ts
implements #719
This PR cleans up some of the documentation viewer internals, and adds a `godotTools.documentation.pageScale` setting.
This also fixes a hilarious bug where the css style for the minimap was accidentally selecting the div for Array.map() and displaying *that* as the minimap.
> Add documentation page scaling feature

- src/lsp/ClientConnectionManager.ts
- src/lsp/GDScriptLanguageClient.ts
- src/lsp/MessageBuffer.ts
- src/lsp/MessageIO.ts
- src/lsp/gdscript.capabilities.ts
This is a dirty fix for #697 and #701
The Godot Language server does not appear to support the `workspace/symbol` rpc method.
This PR simply discards any outgoing LSP message that requests `workspace/symbol`. It's not a good long term solution, but it does prevent really annoying error spam in the editor.
> Suppress "workspace/symbol" not found error

- src/utils/project_utils.ts
RE: #726 
@KoBeWi please grab the CI build and let me know if this solves your problem
> Capitalize the drive letter in windows absolute paths

- src/debugger/godot4/variables/variant_decoder.ts
- src/debugger/godot4/variables/variants.ts
Related to #699.
This is likely the same issue as what's mentioned [here](https://github.com/godotengine/godot-vscode-plugin/issues/699#issuecomment-2372611126), which seems to stem from the fact that `decode_TypedArray` doesn't take into account all the forms that typed arrays can be encoded in.
Typed arrays can conditionally encode either a `uint32_t` as the type, if the array contains a built-in type, or a `String` if the array contains scripts of some kind, and `decode_TypedArray` currently only accounts for the former and not the latter.
This PR fixes this issue by incorporating not only `HEADER_DATA_FIELD_TYPED_ARRAY_BUILTIN`, but also `HEADER_DATA_FIELD_TYPED_ARRAY_CLASS_NAME` and `HEADER_DATA_FIELD_TYPED_ARRAY_SCRIPT`, as found …
> Fix typed arrays of scripts not being decoded properly

- syntaxes/GDScript.tmLanguage.json
See [Variant class](https://docs.godotengine.org/en/latest/contributing/development/core_and_modules/variant_class.html) for a full list of types available as of Godot 4.3.
- This closes https://github.com/godotengine/godot-vscode-plugin/issues/736.
> Add `@static_unload` annotation and Godot 4.3 Variant types to syntax highlighting

- syntaxes/GDScript.tmLanguage.json
The title says all. Related to [Issue #735](https://github.com/godotengine/godot-vscode-plugin/issues/735).
> Fixed the textmate grammar erroneously tagging enum members and const variables as language constants

- src/providers/documentation_builder.ts
> Fix VBox and HBox docs not opening

- src/formatter/snapshots/float_notation.gd
- src/formatter/snapshots/leave_strings_alone.gd
- src/formatter/textmate.ts
- syntaxes/GDScript.tmLanguage.json
Per @AlfishSoftware's [feedback](https://github.com/godotengine/godot-vscode-plugin/pull/746#discussion_r1847281166) or #746, this PR removes the float literal rule I copied from the MagicPython grammar and (hopefully!) fixes the existing float rules.
> Update float syntax rules and formatting

- src/debugger/godot4/variables/variant_decoder.ts
- src/debugger/godot4/variables/variants.ts
- src/debugger/inspector_provider.ts
Adding support for Typed Dictionaries is similar to Typed Arrays from #715. 
This is still ONLY protocol decoding support. Carrying the type information through to the debugger UI will require rewriting a lot of code.
@Calinou Do you know when `4.4-stable` is expected to release? I would like to have this published as `v2.4.0` BEFORE the new engine drops, instead of playing catch-up like usual.
> Add debugger support for Typed Dictionaries

- src/debugger/godot3/debug_session.ts
- src/debugger/godot4/debug_session.ts
Fixes the VSCode watch window freeze due to missing response in case of exception. See related #779
> Fix debugger watch window freeze caused by missing responses

- configurations/snippets.json
Many of the snippets provided by the extension are for Godot 3, and many of them are also not very useful: for instance, there is a snippet to write an "if" statement - which is literally just `if` and then the `condition`. I haven't removed any of the less useful or outdated ones here, but I have provided some that I often use myself to open the discussion on snippets.
I have added the following:
- `void` function shortcut
- `load` and `preload` shortcuts
- Template for a variable with getter and setter (and also a typed version of this)
- Snippet for creating an exported variable in Godot 4
- Snippet for creating a tween
- Snippet for waiting X seconds
> Add some useful GDScript snippets for Godot 4

- media/docs.css
- package.json
- src/providers/documentation.ts
- src/providers/documentation_builder.ts
This adds an option in extension settings to enable/disable documentation minimap. The minimap will be enabled by default.
Enabled
Disabled
> Add setting to enable/disable documentation minimap

- README.md
I've added a few workflow tips to the README. For a workflow that switches between Godot and VSCode, these settings reduce friction, but their existence may not be obvious to someone starting out.
> Add Autosave details and Server Port note to README

- syntaxes/GDScript.tmLanguage.json
In Godot's script editor, region blocks and comments are highlighted in different colors for better readability
this tiny PR just adds a region scope to replicate that behavior 
this also allows regions to be customized as their own separate thing
I'm not familiar with VSCode grammar scopes so apologies if the scope isn't correct
there's also the option of capturing the name part of the region, but I'm not sure what scope that would have to be
> Add region block as a language grammar scope

- src/scene_tools/parser.ts
Nodes can have names, that contain some special characters (including spaces):
But some characters are not allowed:
Based on this list, I changed the regular expression, that parses the scene.
Before:
After:
Fixes #688
> Fix scene preview with nodes, that have spaces in names

- package-lock.json
- package.json
- src/lsp/ClientConnectionManager.ts
- src/lsp/GDScriptLanguageClient.ts
- src/lsp/MessageIO.ts
- src/providers/documentation.ts
- src/providers/inlay_hints.ts
Fixes #799
I think the issue was that VSCode was automatically sending `workspace/didChangeWatchedFiles` rpc messages, which the Godot LSP does not support.
This is the response from the Language Server:
```
Received response message without id: Error is: 
{
"code": -32601,
"message": "Method not found: didChangeWatchedFiles"
}
```
I previously built a system that can inspect and modify incoming and outgoing LSP messages between the socket and VSCode's LSP Client. In this system I was attempting to discard outgoing `workspace/didChangeWatchedFiles`  messages, but I was mistakenly discarding `didChangeWatchedFiles` messages.
> Various LSP Client Improvements

- src/extension.ts
- src/providers/document_drops.ts
- src/providers/document_link.ts
- src/providers/hover.ts
- src/providers/inlay_hints.ts
- src/scene_tools/parser.ts
- src/scene_tools/preview.ts
- src/scene_tools/types.ts
- src/utils/godot_utils.ts
Improves Scene Preview locking by saving the path of the locked scene to workspace storage.
Also implements relative path modification when dragging from the Scene Preview into a script. This resolves #640
Base case, the target script is attached to the scene root:
New case, the target script is attached to some other node in the scene:
> Scene Preview Improvements (relative path drag/drop)

- src/debugger/debugger.ts
Currently, the error message in debug_current_file doesn't tell the user that the scene file and script file must share the same name. This fixes that.
> Change debug_current_file error message

- src/debugger/godot4/variables/variant_decoder.ts
- src/debugger/godot4/variables/variants.ts
Hello,
In some cases the extension would soft lock making it impossible to inspect variables. The symptoms are very similar to #699, except this time the problem is caused by typed dictionaries that have `Variant` as a value type.
To reproduce try setting a breakpoint in the script below and inspecting contents of `my_dict`.
The issue replicates on Godot 4.4 (and possibly newer versions) on both Windows and MacOs.
```
extends Node
func _ready() -> void:
var my_dict: Dictionary[int, Variant] = {5: "abc", 31: "Vector3(5, 6, 7)", 63: "xyzW"}
print("")
```
The solution is to container check type flags and then decode type info only if flag is nonzero. If flag === 0 then there will be no type information included in the buffer.
> Fix extension soft lock when inspecting Dictionary variables with Variant key types

- package.json
- src/debugger/godot4/variables/debugger_variables.test.ts
- src/utils/godot_utils.ts
This is my first attempt at any extension coding, so feel free to give me tips if anything seems off. 
But I noticed that someone had already reported this issue that I also wanted fixed, so it seemed like a good reason to dip my toes in.
Regex section is based on the setup in [vscode-cpptools](https://github.com/microsoft/vscode-cpptools/blob/7e013ab0da5455f6f3734fe7b5a5d2bd4a5a3595/Extension/src/expand.ts#L91) and seems to do the trick. 
Only part I'm unsure about is the section in `debugger_variables.test.ts`. Was there a reason for it not calling `clean_godot_path` previously?
> Added ability to specify editorPath using environment variable (#807)

- src/lsp/ClientConnectionManager.ts
- src/lsp/GDScriptLanguageClient.ts
Fixes https://github.com/godotengine/godot-vscode-plugin/issues/844
Over on the issue a rework of the client was mentioned. This PR is not meant to do this. It's a minimal fix to ensure consistent state, since consistent state is a blocker to move forward with certain refactorings and fixes in the server (e.g. https://github.com/godotengine/godot/pull/105236)
(Also added one unrelated comment to a message filter, since it jumped into my eye)
> Recreate LSP Client to prevent out of sync state
